name: Tests

on:
    push:
    pull_request:
    schedule:
        - cron: '30 7 * * 1'

jobs:
    tests:
        if: (github.event_name == 'schedule' && github.repository == 'e-commit/doctrine-entities-generator-bundle') || (github.event_name != 'schedule')
        strategy:
            fail-fast: false
            matrix:
                include:
                    -   php-version: '7.2'
                        composer-flags: '--prefer-stable --prefer-lowest'
                        description: 'with lowest'
                    -   php-version: '7.2'
                        symfony-version: '^4'
                        description: 'with SF ^4'
                    -   php-version: '7.2'
                        symfony-version: '^5'
                        description: 'with SF ^5'
                    -   php-version: '7.3'
                        symfony-version: '^4'
                        description: 'with SF ^4'
                    -   php-version: '7.3'
                        symfony-version: '^5'
                        description: 'with SF ^5'
                    -   php-version: '7.4'
                        symfony-version: '^4'
                        description: 'with SF ^4'
                    -   php-version: '7.4'
                        symfony-version: '^5'
                        description: 'with SF ^5'
                    -   php-version: '8.0'
                        symfony-version: '^4'
                        description: 'with SF ^4'
                    -   php-version: '8.0'
                        symfony-version: '^5'
                        description: 'with SF ^5'

        name: PHP ${{ matrix.php-version }} ${{ matrix.description }}

        runs-on: 'ubuntu-20.04'

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-version }}
                    extensions: "pdo_sqlite"
                    coverage: none
                    tools: flex
                env:
                    update: true

            -   name: Display versions
                run: |
                    php -r 'foreach (get_loaded_extensions() as $extension) echo $extension . " " . phpversion($extension) . PHP_EOL;'
                    php -i

            -   name: Get Composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config cache-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}-${{ matrix.composer-flags }} #cs
                    restore-keys: |
                        composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}-
                        composer-${{ runner.os }}-${{ matrix.php-version }}-
                        composer-${{ runner.os }}-
                        composer-

            -   name: Configure Symfony Flex
                if: matrix.symfony-version
                run: composer config extra.symfony.require ${{ matrix.symfony-version }}

            -   name: Install dependencies
                run: composer update --no-interaction --no-progress ${{ matrix.composer-flags }}

            -   name: Run PHPUnit
                run: php vendor/phpunit/phpunit/phpunit

            -   name: Run PHP CS Fixer
                env:
                    PHP_CS_FIXER_IGNORE_ENV: 1
                run: php vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --diff --dry-run -v
